language: node_js
node_js: stable
dist: trusty
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
  - npm run dev & wait-on http://localhost:3000
  - $(npm bin)/cypress run --record