language: node_js
node_js: stable
dist: trusty
cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
install:
  - npm install
script:
  - npm run test
  - npm run dev & wait-on http://localhost:3000
  - $(npm bin)/cypress run --record