export const GET_FIRMS_SUCCESS = "GET_FIRMS_SUCCESS";
export const GET_OFFERINGS_SUCCESS = "GET_OFFERINGS_SUCCESS";
export const FILTER_OFFERING = "FILTER_OFFERING";
export const GET_BACK_OFFERING = "GET_BACK_OFFERING";
