export const GET_FIRMS_SUCCESS = "GET_FIRMS_SUCCESS";
export const GET_OFFERINGS_SUCCESS = "GET_OFFERINGS_SUCCESS";

// export const GET_FIRMS_STARTED = "GET_FIRMS";
// export const GET_OFFERINGS_STARTED = "GET_OFFERINGS";
